### ISSUE TITLE
Adds Advisor Layout

### ISSUE THREAD

**Issue by christianhelp** [acmutsa/newbook-next#7]
## Description
Create a basic layout for what the ratings on an advisor will look like (can be based on the previous work found [here](https://rma-layout-shadcn.vercel.app/advisor)

## Requirements
- Ensure the layout has the advisor's ratings. 
- Reference current schema for things to rate advisors from (feel free to suggest new ones)
- Provide the user reviews
- Ensure mobile optimization

**Comment by gataria** [comment]
Going to work on this in the next couple of days, though I'll ask a couple things that can hopefully get me started.

Since we're going to be making components that are distinct from shadcn's, I imagine that we're going to be creating our own in `/apps/web/src/components/ui`. My approach is going to be importing shadcn's components and basically styling them w/ tailwind classes, possibly adding some props and any other additional functionality. 
 - Should the component names follow a specific "branded" naming scheme? e.g., `NewbookCard.tsx` instead of just `card.tsx`?
 - Is it okay if I try and organize the components' folders in some way? There is some advisor-specific stuff (e.g., an AdvisorScore component showing the score w/ styling and some color score indicator) that I would rather have organized in a `Advisor/` folder.
 - Are we going to have any way to declare constants? In my prior job's repo, we had some constants under `lib/constant.ts`, which I think could be helpful here (e.g., `const MAX_SCORE: number = 5` to indicate a maximum advisor score of 5.0)

**Comment by christianhelp** [comment]
So I would recommend that we instead do not create our components in the `/apps/web/src/components/ui` as that is what ShadCN creates to separate out the components we import. Instead, consider creating a `shared` folder that will live under `/apps/web/src/components/shared` and we can keep all of ours there. Typically, it is also good practice to organize your components by where they will be needed hence the justification for a `shared` folder.  Anyways, gonna respond to the rest of the questions in order.

- Regarding naming conventions, I like using the Pascal case (`NewBookCard.tsx`) instead of the lowercase version.
- I like the idea of it as long as you believe there are enough components to do this with. Split / organize things only when it becomes crowded.
- Constants are encouraged with the same naming convention you used for your example. However, there is no need to add the `:number` part to it as typescript is smart enough to infer the type based off of the value and we usually want to defer to the typescript inference instead of our own manual declaration (this goes for functions and such as well)

**Comment by gataria** [comment]
I've been working through this by developing individual components (I should have the actual advisor layout put together soon). I wanted to bring up that adding `shadcn` components seems to modify `pnpm-lock.yaml` and `package.json`. Wanted to ask if this is expected behavior, and if I should be concerned about it at all. Thanks!
![image](https://github.com/user-attachments/assets/c04fe22c-0edd-4bda-8ee2-bab3e31f97f7)

**Comment by christianhelp** [comment]
Yep. Interesting that the bun types also got bumped with it, but each thing you add from shadCn requires new things to be added from radix-UI stuff (which is what ShadCN is built on top of) as well as tailwind stuff on the initial add so you are all good.
